dataset_name: finediving_slide
train_split: ['train']
val_split: ['test']
round: 1000
active_learning_method: uniform # dummy name
dataset: {
  train_json_file: /data3/xiaodan8/FineDiving/annotation/finediving_train_label.txt,
  val_json_file: /data3/xiaodan8/FineDiving/annotation/finediving_test_label.txt,
  num_classes: 29,
  num_frames: 4,
  trunc_thresh: 0.5,
  crop_ratio: [0.9, 1.0],
  max_seq_len: 64,
  window_length: 16,
  window_stride: 8,
  sample_stride: 4,
  use_raw_video: True,
  load_jpg: True,
}
model: {
  fpn_type: identity,
  max_buffer_len_factor: 6.0,
  n_mha_win_size: 9,
}
opt: {
  learning_rate: 0.00005190723388143434,
  epochs: 55,
  weight_decay: 0.05,
}
loader: {
  batch_size: 4,
  num_workers: 8,
}
train_cfg: {
  init_loss_norm: 100,
  clip_grad_l2norm: 1.0,
  cls_prior_prob: 0.01,
  center_sample: radius,
  center_sample_radius: 1.5,
}
test_cfg: {
  voting_thresh: 0.7,
  pre_nms_topk: 2000,
  max_seg_num: 200,
  min_score: 0.001,
  multiclass_nms: True,
}
output_folder: ./ckpt/
